# Generated by Django 6.0.6 on 2026-07-15 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weekly_workouts', 'Weekly Workouts'), ('daily_steps', 'Daily Steps'), ('target_weight', 'Target Weight'), ('weekly_calories', 'Weekly Calories')], max_length=20)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
