# Generated by Django 6.0.6 on 2026-07-15 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('active_minutes', models.PositiveIntegerField(default=0)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date', 'source')},
            },
        ),
    ]
